INFO:__main__:***** Running training *****
INFO:__main__:  Num examples = 319940
INFO:__main__:  Num Epochs = 3
INFO:__main__:  Instantaneous batch size per device = 8
INFO:__main__:  Total train batch size (w. parallel, distributed & accumulation) = 32
INFO:__main__:  Gradient Accumulation steps = 2
INFO:__main__:  Total optimization steps = 20000
Steps:   0%|                                                                                                                                                                         | 0/20000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1665, in <module>
    main()
  File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1551, in main
    for step, batch in enumerate(train_dataloader):
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
    return self._process_data(data)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
    data.reraise()
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
    return [self.dataset[self.indices[idx]] for idx in indices]
  File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 368, in __getitem__
    cropped_images = self.transforms_0(torch.cat([image, conditioning_image], dim=0))
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/container/image.py", line 360, in __call__
    _output_image = decorated_forward(*inputs, **kwargs)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/core/module.py", line 81, in wrapper
    tensor_outputs = func(*args, **kwargs)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/container/base.py", line 304, in forward
    params = self.forward_parameters(out_shape)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/container/image.py", line 242, in forward_parameters
    mod_param = module.forward_parameters(batch_shape)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/base.py", line 218, in forward_parameters
    _params = self.generate_parameters(torch.Size((int(to_apply.sum().item()), *batch_shape[1:])))
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/_2d/geometric/center_crop.py", line 109, in generate_parameters
    return rg.center_crop_generator(batch_shape[0], batch_shape[-2], batch_shape[-1], self.size, self.device)
  File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/random_generator/_2d/crop.py", line 302, in center_crop_generator
    raise AssertionError(f"Crop size must be smaller than input size. Got ({height}, {width}) and {size}.")
AssertionError: Crop size must be smaller than input size. Got (3, 1) and (256, 512).
[rank0]: Traceback (most recent call last):
[rank0]:   File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1665, in <module>
[rank0]:     main()
[rank0]:   File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 1551, in main
[rank0]:     for step, batch in enumerate(train_dataloader):
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/accelerate/data_loader.py", line 454, in __iter__
[rank0]:     current_batch = next(dataloader_iter)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/_utils.py", line 706, in reraise
[rank0]:     raise exception
[rank0]: AssertionError: Caught AssertionError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 50, in fetch
[rank0]:     data = self.dataset.__getitems__(possibly_batched_index)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in __getitems__
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/utils/data/dataset.py", line 420, in <listcomp>
[rank0]:     return [self.dataset[self.indices[idx]] for idx in indices]
[rank0]:   File "/sdb5/SVD_ControlNet_Relight/train_svd_decoder.py", line 368, in __getitem__
[rank0]:     cropped_images = self.transforms_0(torch.cat([image, conditioning_image], dim=0))
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/container/image.py", line 360, in __call__
[rank0]:     _output_image = decorated_forward(*inputs, **kwargs)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/core/module.py", line 81, in wrapper
[rank0]:     tensor_outputs = func(*args, **kwargs)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/container/base.py", line 304, in forward
[rank0]:     params = self.forward_parameters(out_shape)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/container/image.py", line 242, in forward_parameters
[rank0]:     mod_param = module.forward_parameters(batch_shape)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/base.py", line 218, in forward_parameters
[rank0]:     _params = self.generate_parameters(torch.Size((int(to_apply.sum().item()), *batch_shape[1:])))
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/_2d/geometric/center_crop.py", line 109, in generate_parameters
[rank0]:     return rg.center_crop_generator(batch_shape[0], batch_shape[-2], batch_shape[-1], self.size, self.device)
[rank0]:   File "/opt/conda/envs/svd_control_org/lib/python3.9/site-packages/kornia/augmentation/random_generator/_2d/crop.py", line 302, in center_crop_generator
[rank0]:     raise AssertionError(f"Crop size must be smaller than input size. Got ({height}, {width}) and {size}.")
[rank0]: AssertionError: Crop size must be smaller than input size. Got (3, 1) and (256, 512).